name: Release Live Docker
on:
  workflow_dispatch:
  schedule:
    # Every day at the start of the day
    - cron:  '0 0 * * *'

jobs:
  publish:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Chalk
        uses: crashappsec/setup-chalk-action@main
        with:
          password: ${{ secrets.CHALK_PASSWORD }}
          public_key: ${{ secrets.CHALK_PUBLIC_KEY }}
          private_key: ${{ secrets.CHALK_PRIVATE_KEY }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0
      -
        name: Login to DockerHub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: zapbot
          password: ${{ secrets.ZAPBOT_DOCKER_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push Docker image
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
        with:
          context: docker
          file: docker/Dockerfile-live
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: |
            ghcr.io/zaproxy/zaproxy:nightly
            zaproxy/zap-nightly:latest
          secrets: |
            webswing_url=${{ secrets.WEBSWING_URL }}
          annotations: |
            index:org.opencontainers.image.source=https://github.com/zaproxy/zaproxy
            index:org.opencontainers.image.description=The nightly Docker image for the worldâ€™s most widely used web app scanner.
            index:org.opencontainers.image.licenses=Apache-2.0
      - name: "Publicise the release"
        uses: myConsciousness/bluesky-post@96827d0a9604cb228b11b3095f6961196efba4a0 # v5
        if: ${{ ! cancelled() }}
        with:
          text: "The 'Nightly' @zaproxy.org #Docker image has just been updated https://hub.docker.com/r/zaproxy/zap-nightly"  
          identifier: ${{ secrets.BLUESKY_ZAPBOT_IDENTIFIER }}
          password: ${{ secrets.BLUESKY_ZAPBOT_PASSWORD }}
