name: Release Weekly Docker
on:
  workflow_dispatch:
  repository_dispatch:
    types: 'release-weekly-docker'

jobs:
  publish:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          echo "REL_DATE=$(date +%F)" >> $GITHUB_ENV
          echo "REL_DATE_SHORT=$(date +%Y%m%d)" >> $GITHUB_ENV
      - name: Set up Chalk
        uses: crashappsec/setup-chalk-action@main
        with:
          password: ${{ secrets.CHALK_PASSWORD }}
          public_key: ${{ secrets.CHALK_PUBLIC_KEY }}
          private_key: ${{ secrets.CHALK_PRIVATE_KEY }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
      -
        name: Login to DockerHub
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          username: zapbot
          password: ${{ secrets.ZAPBOT_DOCKER_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push Docker image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          context: docker
          file: docker/Dockerfile-weekly
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: |
            ghcr.io/zaproxy/zaproxy:${{ env.REL_DATE_SHORT }}-weekly
            ghcr.io/zaproxy/zaproxy:weekly
            zaproxy/zap-weekly:${{ env.REL_DATE_SHORT }}
            zaproxy/zap-weekly:latest
          secrets: |
            webswing_url=${{ secrets.WEBSWING_URL }}
          annotations: |
            index:org.opencontainers.image.source=https://github.com/zaproxy/zaproxy
            index:org.opencontainers.image.description=The weekly Docker image for the worldâ€™s most widely used web app scanner.
            index:org.opencontainers.image.licenses=Apache-2.0
