name: Release Weekly Docker
on:
  workflow_dispatch:
  repository_dispatch:
    types: 'release-weekly-docker'

jobs:
  publish:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "REL_DATE=$(date +%F)" >> $GITHUB_ENV
          echo "REL_DATE_SHORT=$(date +%Y%m%d)" >> $GITHUB_ENV
      - name: Set up Chalk
        uses: crashappsec/setup-chalk-action@main
        with:
          password: ${{ secrets.CHALK_PASSWORD }}
          public_key: ${{ secrets.CHALK_PUBLIC_KEY }}
          private_key: ${{ secrets.CHALK_PRIVATE_KEY }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0
      -
        name: Login to DockerHub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: zapbot
          password: ${{ secrets.ZAPBOT_DOCKER_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push Docker image
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
        with:
          context: docker
          file: docker/Dockerfile-weekly
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: |
            ghcr.io/zaproxy/zaproxy:${{ env.REL_DATE_SHORT }}-weekly
            ghcr.io/zaproxy/zaproxy:weekly
            zaproxy/zap-weekly:${{ env.REL_DATE_SHORT }}
            zaproxy/zap-weekly:latest
          secrets: |
            webswing_url=${{ secrets.WEBSWING_URL }}
          annotations: |
            index:org.opencontainers.image.source=https://github.com/zaproxy/zaproxy
            index:org.opencontainers.image.description=The weekly Docker image for the worldâ€™s most widely used web app scanner.
            index:org.opencontainers.image.licenses=Apache-2.0
